"""
PROYECTO PROPUESTO DEL CURSO DE PYTHON MES #1
=============================================
- FORMATO DE ENTREGA: CARPETA CON LOS ARCHIVOS_PY
- ZIPEADO AL GRUPO DE WHATSAPP
- DIA FINAL DE ENTREGA:SABADO 2 DE MARZO 12:00 PM

ENUNCIADO
==========
Enunciado: Carrito de Compras en Python

- Crea un programa en Python que simule un carrito de compras simple. El programa debería permitir al usuario realizar las siguientes acciones:

Agregar Producto al Carrito:
============================
- Solicitar al usuario ingresar el nombre del producto, su precio unitario y la cantidad que desea agregar al carrito.
- Si el producto ya existe en el carrito, se debe actualizar la cantidad.
Utiliza un diccionario para almacenar la información del carrito, donde la clave sea el nombre del producto y el valor sea otro diccionario con el precio y cantidad.

Eliminar Producto del Carrito:
=============================

-Solicitar al usuario ingresar el nombre del producto que desea eliminar del carrito.
-Si el producto no está en el carrito, mostrar un mensaje indicando que el producto no existe.

Mostrar Carrito:
===============

-Mostrar al usuario la lista de productos en el carrito con sus respectivos precios y cantidades.
-Calcular y mostrar el total de la compra.

Salir del Programa:
===================

Permitir al usuario salir del programa.

Requisitos Adicionales:
=====================

*Utiliza funciones para modularizar el código.
*Maneja adecuadamente los errores de entrada del usuario.
*El programa debe ejecutarse hasta que el usuario elija salir.

"""